Сервис статистики
SarychV/java-explore-with-me pull request #1
Opened 2023-12-06 08:43 UTC by SarychV

…ики)

2023-12-06 12:29 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/client/src/main/java/ru/practicum/ewm/stats/EwmClient.java
> +public class EwmClient {
этот класс не нужен, точка входа - это класс EwmStat

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/BadHttpResponseException.java
> +public class BadHttpResponseException extends Exception {
BadHttpRequestException

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/TestController.java
> +    @Autowired
аннотация не нужна

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/dto/src/main/java/ru/practicum/ewm/stats/dto/StatResultDto.java
> +    int hits;
private?

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/dto/src/main/java/ru/practicum/ewm/stats/map/DateMapper.java
> +        return "";
тут лучше бы сразу в catch кинуть исключение

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/StatsController.java
> +    @Autowired
не нужна аннотация, потому что final стоит на 19 строке

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/StatsController.java
> +
лишний отступ

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/StatsServiceImpl.java
> +    @Autowired
не нужна

2023-12-06 12:29 UTC, ErkinKasymaliev commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/exception/ExceptionController.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
NotFound, BadRequest разве не надо отлавливать тоже?

2023-12-07 04:04 UTC, SarychV commented on stats/client/src/main/java/ru/practicum/ewm/stats/EwmClient.java
> +public class EwmClient {
Это для тестирования клиента через TestController. Просто вспомогательный. Если мешает я его уберу.

2023-12-07 04:11 UTC, sarychv commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/BadHttpResponseException.java
> +public class BadHttpResponseException extends Exception {
Почему? Это исключение я генерирую при получении ответа методом RestTemplate.exchange() с исключением HttpStatusCodeException в классе StatsClient. Это исключение возникает при ответе на запрос, т.е. в response'e.

2023-12-07 04:13 UTC, SarychV commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/TestController.java
> +    @Autowired
Да, я знаю, потому что контроллер единственный. Но она не ошибка. Если мешает, уберу. Исправил.

2023-12-07 04:22 UTC, SarychV commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/StatsController.java
> +    @Autowired
Исправил.

2023-12-07 04:22 UTC, SarychV commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/StatsController.java
> +
Исправил.

2023-12-07 04:22 UTC, sarychv commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/StatsServiceImpl.java
> +    @Autowired
Исправил.

2023-12-07 04:25 UTC, ErkinKasymaliev commented on stats/client/src/main/java/ru/practicum/ewm/stats/EwmClient.java
> +public class EwmClient {
уберите

2023-12-07 04:28 UTC, ErkinKasymaliev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/TestController.java
> +    @Autowired
уберите

2023-12-07 04:28 UTC, ErkinKasymaliev commented on stats/client/src/main/java/ru/practicum/ewm/stats/client/BadHttpResponseException.java
> +public class BadHttpResponseException extends Exception {
не так понял, ок

2023-12-07 04:41 UTC, SarychV commented on stats/client/src/main/java/ru/practicum/ewm/stats/EwmClient.java
> +public class EwmClient {
Тогда утрачивается смысл в TestController. Я его тоже уберу.

2023-12-07 04:49 UTC, SarychV commented on stats/service/src/main/java/ru/practicum/ewm/stats/service/exception/ExceptionController.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Добавил.

2023-12-07 05:16 UTC, SarychV commented on stats/dto/src/main/java/ru/practicum/ewm/stats/map/DateMapper.java
> +        return "";
Исправил.

2023-12-07 06:06 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-12-08 03:02 UTC, merged