Реализация технического задания третьего этапа дипломного проекта
SarychV/java-explore-with-me pull request #3
Opened 2023-12-24 07:19 UTC by SarychV

Добавлена дополнительная функциональность "Локации"

2023-12-24 08:31 UTC, ErkinKasymaliev requested changes
привет, отличная работа!
Но есть где можно улучшить

2023-12-24 08:31 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsInLocation(
а нам здесь это надо? По идее мы добавляем новую локацию и ивентов у нее быть не может

2023-12-24 08:31 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +                .filter(event -> event.getState().equals(EventState.PUBLISHED))
enum-ы можно сравнивать через ==, также в практике обычно сперва пишет с чем мы хотим сравнивать, вот так:
...` EventState.Published == event.getState()`
_Рекомендательный коммент_

2023-12-24 08:31 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<LocationDtoOutShort> result = selectedLocations.stream()
давайте так перепишем:
```
List<LocationDtoOutShort> result = locationRepository.findAll(PageRequest.of(from, size)).stream()
    .map(LocationMapper::toLocationDtoOutShort)
    .collect(Collectors.toList());
```

лишние переменные даже и в методах можно и не создавать, если метод небольшой, в данном случае читаемость не страдает.
_Рекомендальтеный коммент_

2023-12-24 08:31 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        log.info("Location with id={} was deleted", locationId);
есть вероятность, что `locationRepository.deleteById(locationId)` может завершиться с ошибкой: база будет недоступна, проблемы с транзакциями и так далее, а в логах будет сообщение, что локация удалена, что будет мешать нахождению бага, особенно для тех, у кого нет доступа к коду. Поэтому `log.info("Location with id={} was deleted", locationId);` поставьте в конце метода

2023-12-24 08:31 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +            if (distance(event.getLat(), event.getLon(),
давайте в один if перепишем:
```
if (!eventsInLocation.contains(event) && distance(event.getLat(), event.getLon(), location.getLat(), location.getLon()) <= location.getRadius() {
..
```

2023-12-24 08:31 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +    public static float distance(float lat1, float lon1, float lat2, float lon2) {
можно убрать этот метод в LocationService.java как default -- он будет по умолчанию public static

2023-12-24 08:42 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsInLocation(
У нее могут быть ивенты. Да они прошлые, но привязаны к месту. Для администратора эта информация может быть полезной. В функционале пользователю выдается информация относительно событий, которые опубликованы и произойдут в будущем, а для администратора выводится вся информация. Я хотел было фильтры для администратора сделать, но уже не успеваю.

2023-12-24 08:54 UTC, ErkinKasymaliev requested changes

2023-12-24 08:54 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsInLocation(
Тогда если есть такой ивент, то значит и есть такая локация уже в базе, тогда зачем нам ее перезаписывать? Ведь по идее должна быть уникальность на (lat, lon, radius)

2023-12-24 09:00 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsInLocation(
В задании было предложено обдумать, будет ли при отсутствии соответствующей локации разрешено добавлять события. Я не стал ограничивать возможность создания события отсутствием соответствующей локации. Просто я думаю, что для афишы, локации это дополнительный сервис. Ведь события можно искать и по категориям и по ключевым словам, не критично, что для события отсутствует локация. Это же афиша. Поэтому в базе могут быть события без соотвествующих им локаций. Но если администратор посчитает, что событий действительно много, что место представляет интерес, он может создать отдельную локацию, которая будет ускорять поиск и делать его более удобным. Но это только дополнительный сервис, а не ограничивающее условие. Это в идее моего приложения. Я не хотел бы ограничивать события локациями.

2023-12-24 09:01 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsInLocation(
Все остальные вопросы я просмотрел, спасибо за комментарии, я их обязательно исправлю.

2023-12-24 09:02 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsInLocation(
> В задании было предложено обдумать, будет ли при отсутствии соответствующей локации разрешено добавлять события. Я не стал ограничивать возможность создания события отсутствием соответствующей локации. Просто я думаю, что для афишы, локации это дополнительный сервис. Ведь события можно искать и по категориям и по ключевым словам, не критично, что для события отсутствует локация. Это же афиша. Поэтому в базе могут быть события без соотвествующих им локаций. Но если администратор посчитает, что событий действительно много, что место представляет интерес, он может создать отдельную локацию, которая будет ускорять поиск и делать его более удобным. Но это только дополнительный сервис, а не ограничивающее условие. Это в идее моего приложения. Я не хотел бы ограничивать события локациями.

ну хорошо, понял вас

2023-12-24 09:40 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<LocationDtoOutShort> result = selectedLocations.stream()
А как  можно дебажить возвраты? Временно создавать и удалять после необходимости?

2023-12-24 10:04 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<LocationDtoOutShort> result = selectedLocations.stream()
так, есть такая вещь в intellij Evaluate Expression, который работает в debug режиме
<img width="904" alt="image" src="https://github.com/SarychV/java-explore-with-me/assets/46344024/e50e1393-7b65-4bf3-9f4e-57090485f1c7">

2023-12-25 04:05 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +                .filter(event -> event.getState().equals(EventState.PUBLISHED))
Исправил.

2023-12-25 04:08 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<LocationDtoOutShort> result = selectedLocations.stream()
Спасибо, я им пользовался, когда нужно было вычислить что-то, а таким образом нет. Спасибо!

2023-12-25 04:14 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        List<LocationDtoOutShort> result = selectedLocations.stream()
Исправил.

2023-12-25 04:17 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +        log.info("Location with id={} was deleted", locationId);
Исправил.

2023-12-25 04:32 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +            if (distance(event.getLat(), event.getLon(),
Исправил.

2023-12-25 04:36 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationServiceImpl.java
> +    public static float distance(float lat1, float lon1, float lat2, float lon2) {
Исправил.

2023-12-25 04:51 UTC, SarychV commented
Эркин! Спасибо за работу!

2023-12-25 06:40 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationService.java
> +    static float distance(float lat1, float lon1, float lat2, float lon2) {
`default float distance(float lat1, float lon1, float lat2, float lon2) {...`

2023-12-25 06:42 UTC, ErkinKasymaliev approved these changes
привет, работа принята! Только перед мержем один коммент небольшой поправьте. Поздравляю вам с окончанием курса, желаю вам скорейшего выхода на коммерческие проекты и быстрого профессионального роста!

2023-12-25 08:03 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationService.java
> +    static float distance(float lat1, float lon1, float lat2, float lon2) {
Когда я делаю метод default, компилятор говорит, что default и static не могут быть совмещены: Illegal combination of modifiers: 'static' and 'default'. Static не скрытый модификатор: когда его нет, используется не статический контекст. Мне нужно выбрать между default и static. Поскольку по своей сути метод больше подходит, как статический (его алгоритм не зависит от свойств объекта), я оставляю его static. Переделка в default влечет некоторые неудобства. В частности, при тестировании метода необходимо создавать в тестовом классе необходимое Spring - окружение, хотя практической надобности при тестировании метода в таком окружении нет совсем.

2023-12-25 08:18 UTC, ErkinKasymaliev commented on main/src/main/java/ru/practicum/ewm/locations/LocationService.java
> +    static float distance(float lat1, float lon1, float lat2, float lon2) {
да, вы правы, прошу прощения

2023-12-25 08:22 UTC, SarychV commented on main/src/main/java/ru/practicum/ewm/locations/LocationService.java
> +    static float distance(float lat1, float lon1, float lat2, float lon2) {
Желаю удачи по жизни! Всего доброго!

2023-12-25 09:22 UTC, merged